INSERT INTO ttlive.region(name, description) VALUES
('DTTB', 'DTTB'),
('BaTTV', 'Baden'),
('ByTTV', 'Bayern'),
('TTVB', 'Brandenburg'),
('FTTB', 'Bremen'),
('HaTTV', 'Hamburg'),
('HeTTV', 'Hessen'),
('TTVMV', 'Mecklenburg-Vorpommern'),
('TTVN', 'Niedersachsen'),
('PTTV', 'Pfalz'),
('RTTVR', 'Rheinland Rheinhessen'),
('STTB', 'Saarland'),
('TTVSA', 'Sachsen-Anhalt'),
('TTTV', 'Thüringen'),
('WTTV', 'NRW'),
('TTBW', 'Baden-Württemberg');